export const TRANSACTION_BLOCK_TYPE = {
  ASSET_BRIDGE: 'ASSET_BRIDGE' as const,
  SEND_ASSET: 'SEND_ASSET' as const,
  ASSET_SWAP: 'ASSET_SWAP' as const,
  KLIMA_STAKE: 'KLIMA_STAKE' as const,
  PLR_DAO_STAKE: 'PLR_DAO_STAKE' as const,
  PLR_STAKING_V2: 'PLR_STAKING_V2' as const,
  HONEY_SWAP_LP: 'HONEY_SWAP_LP' as const,
  DISABLED: 'DISABLED' as const,
};

export type TRANSACTION_BLOCK_TYPE_KEY = keyof typeof TRANSACTION_BLOCK_TYPE;
