export interface Theme {
  color?: {
    background?: {
      main?: string,
      topMenu?: string,
      topMenuButton?: string,
      card?: string,
      selectInput?: string,
      selectInputExpanded?: string,
      selectInputScrollbar?: string,
      selectInputScrollbarHover?: string,
      selectInputScrollbarActive?: string,
      selectInputImagePlaceholder?: string,
      selectInputToggleButton?: string,
      textInput?: string,
      switchInput?: string,
      switchInputActiveTab?: string,
      switchInputInactiveTab?: string,
      button?: string,
      closeButton?: string,
      pill?: string,
    },
    text?: {
      main?: string,
      topBar?: string,
      topMenu?: string,
      card?: string,
      cardDisabled?: string,
      cardTitle?: string,
      innerLabel?: string,
      outerLabel?: string,
      selectInput?: string,
      selectInputOption?: string,
      selectInputOptionSecondary?: string,
      selectInputImagePlaceholder?: string,
      textInput?: string,
      textInputSecondary?: string,
      switchInputActiveTab?: string,
      switchInputInactiveTab?: string,
      button?: string,
      buttonSecondary?: string,
      errorMessage?: string,
      searchInput?: string,
      searchInputSecondary?: string,
      pill?: string,
      pillValue?: string,
    },
  }
}

export const defaultTheme: Theme = {
  color: {
    background: {
      main: 'linear-gradient(to right, #f43b40, #f8793f)',
      card: '#fff7f2',
      topMenu: '#fff',
      topMenuButton: '#fff',
      selectInput: '#fff',
      selectInputExpanded: '#fff',
      selectInputScrollbar: '#ff7733',
      selectInputScrollbarHover: 'rgba(255, 119, 51, 0.8)',
      selectInputScrollbarActive: 'rgba(255, 119, 51, 0.5)',
      selectInputImagePlaceholder: '#ffe6d9',
      selectInputToggleButton: '#0a1427',
      textInput: '#ffe6d9',
      switchInput: '#ffd2bb',
      switchInputActiveTab: '#fff',
      switchInputInactiveTab: 'transparent',
      button: '#fff',
      closeButton: '#0a1427',
      pill: '#fff7f2',
    },
    text: {
      main: '#fff',
      topBar: '#fff',
      topMenu: '#191726',
      cardTitle: '#191726',
      card: '#000',
      cardDisabled: '#ddd',
      innerLabel: '#6e6b6a',
      outerLabel: '#6e6b6a',
      selectInput: '#000',
      selectInputOption: '#191726',
      selectInputOptionSecondary: '#191726',
      selectInputImagePlaceholder: '#6e6b6a',
      textInput: '#000',
      textInputSecondary: '#6e6b6a',
      switchInputActiveTab: '#191726',
      switchInputInactiveTab: '#6e6b6a',
      button: '#191726',
      buttonSecondary: '#ffeee6',
      errorMessage: '#ff0000',
      searchInput: '#ff7733',
      searchInputSecondary: '#ff7733',
      pill: '#6e6b6a',
      pillValue: '#191726',
    },
  }
};
